### create a new user
POST http://localhost:3005/user/registerUser
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "smithdoe3@gmail.com",
    "password": "password",
    "phone": "1234567890"
}

### Get all users
GET http://localhost:3005/user/getAllUsers


###get user details
Get http://localhost:3005/user/getUserById
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdlNDdiMjM4LWU0OTktNDExZS05MWU3LTc3M2NiMjkwYjIzMSIsImVtYWlsIjoiam9obmRvZUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyMDg1OTkyNiwiZXhwIjoxNzIwODYzNTI2fQ.7QSb0Y3_eL5fvndRgpjO0lIkgmCOhkTqttyW68f0q84

###update user details
PUT http://localhost:3005/user/updateinfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdlNDdiMjM4LWU0OTktNDExZS05MWU3LTc3M2NiMjkwYjIzMSIsImVtYWlsIjoiam9objEyQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzIwODYzOTc4LCJleHAiOjE3MjA4Njc1Nzh9.hl5jwassHku6Pkhc-1tn1CREE-OU55fnyD-fEBksY44
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "john121@gmail.com",
    "password": "password",
    "phone": "1234567892"
}

###deactivate account
PUT http://localhost:3005/user/deactivateAccount
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4OTJiN2JkLTMwZDktNGEyNy1hNTU2LTNiMGU1MjM3OTRkYSIsImVtYWlsIjoic21pdGhkb2UxQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcyMDg3Nzc2NywiZXhwIjoxNzIwODgxMzY3fQ.NzPB9JHo9yKt4fq3mnXka3qcewZsrsdsrLpOq3Q9x1Q


###request role change
POST  http://localhost:3005/user/requestRoleChange
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM2NWNkYzVjLTVjYWEtNGE5Zi04YjcwLWJmYTEzZjc4MmZlNSIsImVtYWlsIjoic21pdGhkb2UzQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzIwODc2NzI2LCJleHAiOjE3MjA4ODAzMjZ9.2Glec27LFd5dz69t1mNs-2qHnuxynIRRpu60x6iItZs
Content-Type: application/json

{
    "role": "admin"
}



### update role change
POST http://localhost:3005/user/admin/approveRoleChangeRequest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4OTJiN2JkLTMwZDktNGEyNy1hNTU2LTNiMGU1MjM3OTRkYSIsImVtYWlsIjoic21pdGhkb2UxQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcyMDg3NDk2OSwiZXhwIjoxNzIwODc4NTY5fQ.SPYexCCARw1E_-Ucf7m7mZcmMJJLASrM0rArbqHTWW4
Content-Type: application/json

{
  "request_id": "edc953a2-29e4-4ef5-ba63-982c398e0d8b",
  "approve": true
}
08c11909-757b-41db-9fe8-c20a4c5ae405